export enum LOCOMOTION {
  RUNNING = 'RUNNING',
  JUMPING = 'JUMPING',
  DODGING = 'DODGING',
  FALLING = 'FALLING',
}

export enum ANIMATION_STATES {
  LOCOMOTION = 'LOCOMOTION',
  IDLE = 'IDLE',
  TAUNT = 'TAUNT',
  ATTACK = 'ATTACK',
  ABILITY = 'ABILITY',
  DEATH = 'DEATH',
  DAMAGED = 'DAMAGED',
  POSE = 'POSE',
  ATTACK_TRANSITION = 'ATTACK_TRANSITION',
  INTERRUPTED = 'INTERRUPTED', // General state for being interrupted
}

export enum ATTACK_LEVELS {
  STANDING_LIGHT = 'STANDING_LIGHT',
  STANDING_MEDIUM = 'STANDING_MEDIUM',
  STANDING_HEAVY = 'STANDING_HEAVY',
  AERIAL_LIGHT = 'AERIAL_LIGHT',
  AERIAL_MEDIUM = 'AERIAL_MEDIUM',
  AERIAL_HEAVY = 'AERIAL_HEAVY',
  STANDING_SPECIAL = 'STANDING_SPECIAL',
  AERIAL_SPECIAL = 'AERIAL_SPECIAL',
}

export enum SOUND_CATEGORIES {
  VOICE_FX = 'VOICE_FX',
  SOUND_FX = 'SOUND_FX',
  MUSIC = 'MUSIC',
}

export enum SOCKET_EVENTS {
  CONNECTION = 'connection',
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  HELLO = 'hello',
  PLAYERS = 'players',
  CHARACTERS = 'characters',
  MOVE = 'move',
}

export enum INPUT_DEVICES {
  KEYBOARD = 'KEYBOARD',
  GAMEPAD = 'GAMEPAD',
  TOUCH = 'TOUCH',
}

export enum CAMERA_MODES {
  GAME = 'GAME',
  CUTSCENE = 'CUTSCENE',
  MENU = 'MENU',
}
